name: Update File

on:
  workflow_dispatch:
    inputs:
      new_content:
        description: 'New content to write to the file'
        required: true

jobs:
  update_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update File
        run: |
          # Get input values
          file_path="index.html"
          new_content="${{ github.event.inputs.new_content }}"

          # Update the file
          echo "$new_content" > "$file_path"

          # Commit and push changes
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add "$file_path"
          git commit -m "Update $file_path"
          git push
